require_relative "./lib/mastermind.rb"
require_relative "./lib/random.rb"
require_relative "./lib/game.rb"
require_relative "./lib/game_api.rb"

require "net/http"
require "pry"
require "colorize"
require "json"
#require "gosu"